spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        min-idle: 2
        max-idle: 20
        max-wait: 3000

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml



url:
  white-list:
    - 123
    - /auth/**
    - /usr/login
    - /**




